name: server-lint

on: [pull_request]

defaults:
  run:
    working-directory: server

jobs:
  serverlint:
    name: server-lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: add dependencies
        run: yarn --prefer-offline

      - name: Run linter
        run: yarn run lint
